# This file was generated by LetItGo.
class Seedr < Formula
  desc "Seedr helps you to get started quickly. Seedr can setup a project skeleton for you in seconds."
  homepage "https://github.com/sourceseed/seedr"

  version "0.1.5"
  url "https://github.com/sourceseed/seedr/releases/download/0.1.5/darwin_amd64.zip"
  sha256 "5ba48c0ec05a0afa1459cbdcb9933df95d0ee69917b9d0e8e6778ce079593e3b"

  def install
    bin.install "seedr"
  end


  test do
    system "#{bin}/seedr -h"
  end
end
